name: Auto Post Instagram

on:
  schedule:
    - cron: '42 9 * * *'

  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: sudo apt-get install -y fonts-noto-color-emoji

      - name: Install Python dependencies
        run: pip install google-genai requests Pillow cloudinary cryptography pynacl

      - name: Run post script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python post.py
